GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYkB0aGUuYnVpbGRlciIsImlkIjo2LCJpYXQiOjE2NDMyMTk2NDF9.Z8A_i7XG3MVnwUCfddepNrmiLvuIsBZevzneiH_xMxo

{
  "author": "can",
  "url": "he",
  "title": "fix react"
}
###
DELETE http://localhost:3001/api/blogs/15
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVtYWlsQHVzZXJuYW1lLnRlc3QiLCJpZCI6NSwiaWF0IjoxNjQzMjAxNzUxfQ.Bszjqic9kLvOLQaVVXZHaS5Oxm9ntOXhuT7nqelL9MM
###
PUT http://localhost:3001/api/blogs/2
Content-Type: application/json

{
  "likes": 2
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "bob@the.builder",
  "password": "abcdefg",
  "name": "abcdefg"
}
###
GET http://localhost:3001/api/users
###
PUT http://localhost:3001/api/users/username
Content-Type: application/json

{
  "username": "A@username.validation"
}
###
DELETE http://localhost:3001/api/users/4
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "bob@the.builder",
  "password": "abcdefg"
}
### test query string parameters
GET http://localhost:3001/api/blogs?search=react
###
GET http://localhost:3001/api/authors