GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAdGhlLmJ1aWxkZXIiLCJpZCI6MiwiaWF0IjoxNjQzNjM3NzE0fQ.N4xTbZlPvBIBDdZ_Nzj3lDxvfDG4jSwCo_x-EdP1K-o

{
  "author": "can",
  "url": "he",
  "title": "fix react",
  "year": "2000"
}
###
DELETE http://localhost:3001/api/blogs/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYkB0aGUuYnVpbGRlciIsImlkIjoxLCJpYXQiOjE2NDM2MzA1NTN9.sWyKS8ZpZ_CWJCTWnbCo1_HzSccHZZv--GrPi4SPYek
###
PUT http://localhost:3001/api/blogs/3
Content-Type: application/json

{
  "likes": 1
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "bob@the.builder",
  "password": "abcdefg",
  "name": "abcdefg"
}
###
GET http://localhost:3001/api/users
###
PUT http://localhost:3001/api/users/username
Content-Type: application/json

{
  "username": "A@username.validation"
}
###
DELETE http://localhost:3001/api/users/4
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "test@the.builder",
  "password": "abcdefg"
}
### test query string parameters
GET http://localhost:3001/api/blogs?search=react
###
GET http://localhost:3001/api/authors
###
POST http://localhost:3001/api/readinglists
Content-Type: application/json

{
  "blogId": "1",
  "userId": "a"
}
###
GET http://localhost:3001/api/users/2
###
PUT http://localhost:3001/api/readinglists/2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYkB0aGUuYnVpbGRlciIsImlkIjoxLCJpYXQiOjE2NDM2MzA1NTN9.sWyKS8ZpZ_CWJCTWnbCo1_HzSccHZZv--GrPi4SPYek
Content-Type: application/json

{
  "read": true
}
### test query string parameters
GET http://localhost:3001/api/users/2?read=false
###
DELETE http://localhost:3001/api/logout
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYkB0aGUuYnVpbGRlciIsImlkIjoxLCJpYXQiOjE2NDM2MzA1NTN9.sWyKS8ZpZ_CWJCTWnbCo1_HzSccHZZv--GrPi4SPYek
###
PUT http://localhost:3001/api/users/disable/test@the.builder
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYkB0aGUuYnVpbGRlciIsImlkIjoxLCJpYXQiOjE2NDM2Mzc2NDV9.l_b_lfRb15NPSXHK-6DAsbEAxgf2u2V6xwUwvxAP_Tc
Content-Type: application/json

{
  "disabled": false
}